mindmap
  软件工程
    第三章 需求分析
      一、需求分析概述 [1]
      需求分析的重要性 [5]
      二、需求分析的任务 [1]
      1、确定系统的综合要求 [1]
      o 功能要求 o 性能要求 o 可靠性和可用性要求 o 出错处理要求 o... [1]
      需求分析的任务 [1]
      3、导出系统的逻辑模型 需求分析的任务 [1]
      需求分析的任务--举例 [1]
      图书馆的需求分析流程 [1]
      三、与用户沟通获取需求的方法 [1]
      与用户沟通获取需求的方法 [6]
      1、访谈 [1]
      回溯时常遇到的问题 [1]
      复查分析结果 [1]
      面向数据流自顶向下求精过程 [1]
      面向数据流方法的分析举例 [1]
      面向数据流方法的分析的应用 [1]
      四、分析建模与规格说明 [1]
      分析建模与规格说明 [3]
      五、实体-联系图 [6]
      六、数据规范化 [5]
      七、状态转换图 [4]
      基本符号 [3]
      八、其他图形工具 [1]
      层次方框图 [1]
      公司全部产品的数据结构 [1]
      Warnier 图 [1]
      一个Warnier图的例子 [1]
      IPO图 [1]
      IPO [1]
      一 个 IPO 图 的 例 子 [1]
