mindmap
  软件工程
    第五章 总体设计（2） [4]
      输出 主加工 输入 变换型数据流图 [1]
      集中式事务型数据流图 [1]
      结构化设计 [1]
        5.5.2 变换分析 [1]
      1、复查基本 [1]
      系统模型 [1]
      数据流图 [1]
      3、确定数据流 图的类型 [1]
      4、确定输入流和 输出流的边界,孤 立变换中心 [1]
      5、第一级分解 [1]
      o 目的：确保系统的 [1]
      输入数据和输出数 据符合实际。 o 措施：重新检查数 [1]
      据流图。 [1]
      o 精化原则 [1]
      n 确保能够反映目 [1]
      标系统的正确的 逻辑模型。 n 应该使数据流图 [1]
      中每个处理都代 表一个规模适中 的并且相对独立 的子功能。 [1]
      从图中可以看 出，数据沿着两条 输入通路进入系统 ，然后沿着五条通 路离... [1]
      可以认为这个 数据流图的类型是 变换型数据流图。 [1]
      4、确定输入流和输出流的边界，从而孤立出变换中心 [1]
      rpm 不同的人选择 不同的分界点 [1]
      应该在能够完成控制功能并且保持好的耦合和内 聚特性的前提下，尽量使第一级... [1]
      6、进行“第二级分解” [1]
      第二级分解的方法 [1]
      第二级分解的结果： [1]
      接收 传感器信号 [1]
      未经精化的输入结构 未经精化的变换结构 [1]
      6、进行“第二级分解” △SPS [1]
      驱动仪表板 [1]
      未经精化的输出结构 [1]
        （3）模块“加速／减速显示”可以相 应地放在模块“显示mph”的下面。 [1]
      精化的数字仪表板系统的软件结构 [1]
      数字仪表板 [1]
      控制 [1]
      显示 [1]
        4.5.3 事务分析 [1]
      事务分析映射方法 [1]
      事务 中心 [1]
      举例：事务型转换结构图 [1]
      MT
        （2）主图是事务型，子图是变换型 [1]
      Step-2 确定输入数据流和输出流的边 界，从而孤立变换中心 [1]
      主控模块。 [1]
      Step-4 完成“第二级分解” [1]
      Step-5 优化 [1]
      最终的软件结构图如下： [1]
      面向数据流设计方法总结 [1]
        4.5.4 设计优化 [5]
