mindmap
  软件工程
    第六章 详细设计
      详细设计概述 [5]
      详细设计的参与者 [1]
      学习目标 [1]
      6.1 结构程序设计 [3]
      “结构化”起源：对GOTO的认识 [1]
      1. 自顶向下,逐步求精 [1]
      2.有限制的使用GOTO语句 [1]
      举例 [1]
      o 顺序结构，先执行A再执行B o IF_THEN_ELSE型选择（分支... [1]
      DO_CASE型多分支结构和DO_UNTIL型循环 结构。 [1]
      6.2 人机界面设计 [1]
      菜单 [1]
      图像 [1]
      对话框 [1]
      窗口 [1]
      下图描述了一个包括多个部件的窗口 [1]
        6.2.1 设计问题 [1]
      具体设计帮助设施时，需要确定
        6.2.2 设计过程 [1]
      评估标准 [1]
        6.2.3 人机界面设计指南 [1]
      一般交互指南 [1]
      信息显示指南 [1]
      信息显示界面设计 [1]
      数据输入指南 [1]
      数据输入界面设计 [2]
      根据调研资料直接设计某些表，满足第三范式 [1]
      6.3 过程设计的工具
        6.3.1 程序流程图（Program Flow Chart） [1]
      五种基本控制结构 [1]
      将下面给出的伪码转换为流程图 [1]
        6.3.2 盒图（N-S图） [1]
      五种基本控制结构
        6.3.3 PAD图 [1]
      上分支为真 [1]
      使用PAD图提供的def功能逐步求精 [1]
      举例：将下列伪代码转换成PAD表示 [1]
      判定表的组成 [1]
      o 问题描述：“…某公司规定，对于大于70马 [1]
      o 缺点： [1]
        6.3.5 判定树 [1]
      判定树
        6.3.6 过程设计语言 [1]
      过程设计的工具 [6]
      PDL语言 [1]
      各种工具的比较 [1]
      6.5 程序复杂性定量度量 [1]
      定量度量程序复杂性的价值
        （1） 把程序的复杂程度乘以适当常数即可估 [1]
      程序复杂性含义 [1]
        5.5.1 McCabe方法 [1]
      流图 [4]
      顺序结构的结点可以合并 [1]
        （2） 流图G的环形复杂度 [1]
      o 根据程序流程图计算 [1]
      环形复杂度计算的例子 [1]
      即:11-9+2=4
        5.5.2 Halstead方法 [1]
      程序的潜在错误 [1]
