mindmap
  软件工程
    第一章 软件工程学概述（下）
      1.4 软件生命周期 [1]
      软件生命周期各阶段的任务 [1]
      SDLC [1]
      软件生存期各阶段的任务 [3]
      SDLC 3. 软件设计 [3]
      SDLC 3. 系统设计 [1]
      1、问题定义和可行性研究 [1]
      一、软件工程学概述 [1]
      软件过程 [7]
      瀑布模型 [4]
      瀑布模型的表现 [2]
      瀑布模型的缺点 [1]
      瀑布模型适用情况 [1]
      快速原型模型 [4]
      迭代与增量的概念 [4]
      迭代模型的代表 [1]
      螺旋模型 [1]
      螺旋模型的优点 [1]
      螺旋模型的缺点 [1]
      选择螺旋模型的场景 [1]
      螺旋模型适合的项目 [1]
      喷泉模型 [4]
      软件生命周期各模型特点： [1]
      开发模型总结 [1]
      Rational 统一过程 [7]
      敏捷联盟宣言 [7]
      XP（极限编程）模型的特点 [1]
      XP（极限编程）模型的优缺点 [1]
        （1）XP模型作为一种新的模型，在实际应用中还存在着一些问题， 引起了许... [1]
      微软软件生命周期 [1]
