mindmap
  软件工程
    第二章 可行性研究 [1]
      2.1 可行性研究的任务 [4]
      可行性研究的任务归纳 [1]
      2.2 可行性研究的过程 [1]
      3、导出高层逻辑模型（conceptual design） [1]
      5、导出和评价供选择的方案 [1]
      当前系统 [1]
      技术可行性 [1]
      经济可行性 [1]
      操作可行性 [1]
      社会可行性 [1]
      方案选择 [1]
      可行性分析的结论 [1]
        （4）不能进行或不必进行；例如因技术不成熟，经济上不合算或可能 产生负面... [1]
      可行性报告 [2]
      o 反映数据在各部分物理部件间流动的情况 [1]
      2.4 数据流图 [1]
      数据流图作用 [1]
      数据流图符号 [1]
        1.2.1 加工名 [1]
      还有一些辅助的图例: [1]
      * C [1]
      数据流图举例-1 [1]
      文件表示的约定 [1]
      数据源或终点 [3]
      案例-订货系统
        （1）确定外部实体、输入/输出数据流和处理， 画出顶层数据流图。 [1]
      案例-订货系统
        （2）分解顶层数据流图 [1]
      案例-订货系统
        （3）确定数据存储 [1]
      案例-订货系统 [1]
      图书销售系统 [1]
      n 销售子系统 [1]
      o 采购子系统 [1]
      数据字典 [1]
      数据词典的定义方法 [1]
      定义数据的方法—符号 [4]
      数据流的描述 [1]
      数据元素的描述 [1]
      举例 [1]
      105.258 104.264 [1]
      可以拨分机号和外线号码。分机号是从7201~7299。 [1]
      定义（即组成）。 [2]
      成本估计 [4]
      成本/效益分析的方法 [2]
      纯收入 [1]
      投资回收率 [4]
