mindmap
  软件工程
    第五章 总体设计 [1]
      软件设计概述 [1]
      总体设计概述 [1]
      方案设计 [1]
      总体设计过程 [10]
      5.2 设计原理 [1]
      5.2 设计原理
        5.2.1 模块化 [1]
      模块化的依据 [1]
      模块化和软件成本 [1]
        5.2.2 抽象 [1]
      抽象层次 [1]
      软件过程抽象 [4]
      抽象层次Ⅲ. [1]
        5.2.3 逐步求精 [1]
      逐步求精策略 [1]
        5.2.4 信息隐藏和局部化 [3]
        5.2.5 模块独立 [1]
      模块独立的概念 [1]
      1、耦合 [1]
      数据耦合 [1]
      特征耦合 [1]
      特征耦合改为数据耦合举例 [1]
      改控制耦合为数据耦合举例 [1]
      公共耦合 [1]
        （1） 一个模块直接访问另一个模块的内部数据; （2） 一个模块不通过正... [1]
      耦合小结 [1]
      五、模块独立--- 耦合 [1]
      模块2 [1]
      耦合设计原则 [1]
      2、内聚 [1]
      功能内聚 10分 [1]
      中的一部分依赖于另外一部分。因此具有较 好的内聚性。 [1]
      通信内聚例子 [1]
      逻辑内聚 1分 [1]
      5.3 启发式规则 [1]
      消除重复功能 [1]
      2. 模块规模应该适中 [1]
      3. 深度、宽度、扇出、扇入都应适当 [1]
      扇出和扇入 [4]
      避免平铺结构 [1]
      接或间接从属于它的模块的集合。 [1]
      控制范围与作用范围举例 [3]
      5.4 图形工具 [1]
      酒店管理信息系统的层次图 [2]
      举例:说明图书馆系统功能图（H图） [1]
      举例:说明图书馆系统功能图（IPO图） [1]
      结构图 [4]
