mindmap
  软件工程
    第七章 实 现（一）
      软件生命周期 [1]
      7.1 编码 [1]
      编码总体要求 [1]
        7.1.1 选择程序设计语言 [1]
      汇编语言和高级语言 [4]
        7.1.2 编码风格 [6]
      通用规则 [3]
      序言性注解 [1]
      序言性注解举例 [4]
      按类型说明变量 [3]
      3. 语句构造 [7]
      输入和输出 [1]
      5. 效率 [1]
        （1）程序运行时间 [1]
      用于提高运行效率的原则 [1]
        （2）存储器效率 [1]
        （3）输入输出的效率 [3]
