mindmap
  软件工程
    软件维护 [1]
    8.1 软件维护的定义 [6]
    软件维护的类型 [2]
    8.2 软件维护的特点 [1]
      8.2.1 结构化维护与非结构化维护差别巨大 [1]
      8.2.2 维护的代价高昂 [3]
    软件维护的副作用
      8.2.3 维护的问题很多 [1]
    8.3 软件维护过程 [1]
    8.4 软件的可维护性 [1]
      8.4.1 决定软件可维护性的因素 [5]
    5. 可重用性 [1]
      8.4.2 文档 [1]
      8.4.3 可维护性复审 [7]
    8.5 预防性维护 [4]
    2. 文档重构 [1]
    3. 逆向工程 [1]
    • 逆向工程的过程从源代码重构开始，将无结构的源代码转换为结构化的源 代... [4]
